export interface ValidatorConfig {
    name: string;
    definition: string;
    isDirectGroupValidator: boolean;
}

export enum DataTypeValidator {
    AnyURI = 'anyURI',
    Base64Binary = 'base64Binary',
    Byte = 'byte',
    Curie = 'curie',
    Date = 'date',
    DayTimeDuration = 'dayTimeDuration',
    Decimal = 'decimal',
    Double = 'double',
    Duration = 'duration',
    Float = 'float',
    GDay = 'gDay',
    GMonth = 'gMonth',
    GMonthDay = 'gMonthDay',
    GYear = 'gYear',
    GYearMonth = 'gYearMonth',
    HexBinary = 'hexBinary',
    Int = 'int',
    Integer = 'integer',
    LangString = 'langString',
    Long = 'long',
    NegativeInteger = 'negativeInteger',
    NonNegativeInteger = 'nonNegativeInteger',
    NonPositiveInteger = 'nonPositiveInteger',
    PositiveInteger = 'positiveInteger',
    Short = 'short',
    Time = 'time',
    UnsignedByte = 'unsignedByte',
    UnsignedInt = 'unsignedInt',
    UnsignedLong = 'unsignedLong',
    UnsignedShort = 'unsignedShort',
    YearMonthDuration = 'yearMonthDuration',
}

export enum GenericValidator {
    DeconstructionRule = 'deconstructionRule',
    Number = 'number',
    Required = 'required',
    UniqueValues = 'uniqueValues',
}

export enum DataType {
    AnyURI = 'anyURI',
    Base64Binary = 'base64Binary',
    Boolean = 'boolean',
    Byte = 'byte',
    Curie = 'curie',
    Date = 'date',
    DateTime = 'dateTime',
    Decimal = 'decimal',
    DateTimeStamp = 'dateTimeStamp',
    DayTimeDuration = 'dayTimeDuration',
    Double = 'double',
    Duration = 'duration',
    Float = 'float',
    GDay = 'gDay',
    GMonth = 'gMonth',
    GMonthDay = 'gMonthDay',
    GYear = 'gYear',
    GYearMonth = 'gYearMonth',
    HexBinary = 'hexBinary',
    Int = 'int',
    Integer = 'integer',
    PositiveInteger = 'positiveInteger',
    LangString = 'langString',
    Long = 'long',
    NegativeInteger = 'negativeInteger',
    NonNegativeInteger = 'nonNegativeInteger',
    NonPositiveInteger = 'nonPositiveInteger',
    Short = 'short',
    String = 'string',
    Time = 'time',
    UnsignedByte = 'unsignedByte',
    UnsignedInt = 'unsignedInt',
    UnsignedLong = 'unsignedLong',
    UnsignedShort = 'unsignedShort',
    YearMonthDuration = 'yearMonthDuration',
}
