////
Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH

See the AUTHORS file(s) distributed with this work for additional information regarding authorship.

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/
SPDX-License-Identifier: MPL-2.0
////

= Adding internationalization to the project

=== What does internationalization mean?
Internationalization is the process of supporting multiple languages in your applications.
This can be accomplished in an Angular application through third-party libraries, such as _@ngneat/transloco_, or you
can use the built-in i18n functionality.

The command explained below does all the necessary work to prepare the Angular application to support this feature
without any other requirements.

=== Adding internationalization to an Angular app using schematics

Create a new Angular application using the command:

[source]
ng new app demo-schematics

NOTE: Before running any schematics command make sure you are in the Angular project folder with an `angular.json` configuration file.

In the `demo-schematics` project folder run:
[source]
ng generate @esmf/semantic-ui-schematics:i18n

Afterwards the project can translate a UI using https://github.com/jsverse/transloco[@ngneat/transloco,window=_blank,opts=nofollow].
