name: "Create Tagged Release"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true

env:
  RELEASE_VERSION: ${{ github.event.inputs.release_version }}

permissions: {}

jobs:
  gh_tagged_release:
    name: Create tagged release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup NodeJs
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
        with:
          node-version: '22'

      - name: Set versions
        run: |
          release_version=${{ env.RELEASE_VERSION }}
          release_branch_name=${release_version%.*}.x
          echo "release_branch_name=$release_branch_name" >> $GITHUB_ENV

      - name: Set antora version
        run: yq eval -i '.version = "${{ env.RELEASE_VERSION }}"' documentation/js-sdk-guide/antora.yml

      - name: Commit version changes and push to upstream repository
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          branch: ${{ env.release_branch_name }}
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
          commit_author: Author <actions@github.com>
          file_pattern: 'documentation/js-sdk-guide/antora.yml'

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Set app version
        run: npm version ${{ env.RELEASE_VERSION }} --no-git-tag-version

      - name: Build Project
        run: npx nx build schematic

      # This should be removed as soon as we go towards nodejs package repository
      - name: Pack Project as tgz
        run: |
          cp LICENSE dist/libs/schematic/LICENSE
          cd dist/libs/schematic
          sed -i 's/"version": "1.0.0"/"version": "${{ env.RELEASE_VERSION }}"/' package.json
          npm pack
          mv esmf-semantic-ui-schematics-${{ env.RELEASE_VERSION }}.tgz ../../../

      - name: "Create Github release (full)"
        if: ${{ !contains( env.RELEASE_VERSION, '-rc' ) }}
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        id: esmf_sdk_js_release
        with:
          body: "Release version ${{ env.RELEASE_VERSION }}."
          tag_name: v${{ env.RELEASE_VERSION }}
          target_commitish: ${{ env.release_branch_name }}
          draft: false
          prerelease: false
          files: esmf-semantic-ui-schematics-${{ env.RELEASE_VERSION }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: "Create Github release (milestone)"
        if: contains( env.RELEASE_VERSION, '-rc' )
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        id: sds_sdk_js_release
        with:
          body: "Release version ${{ env.RELEASE_VERSION }}."
          tag_name: v${{ env.RELEASE_VERSION }}
          target_commitish: ${{ env.release_branch_name }}
          draft: false
          prerelease: true
          files: esmf-semantic-ui-schematics-${{ env.RELEASE_VERSION }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
